controller_manager:
  ros__parameters:
    update_rate: 100
    use_sim_time: true

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    pantilt_controller:
      type: forward_command_controller/ForwardCommandController

pantilt_controller:
  ros__parameters:
    joints:
      - pan_joint
      - tilt_joint
    interface_name: position